#Requires -Version 5.1
# Rebuild: powershell -ExecutionPolicy Bypass -File flareflow-app-snapshot/tools/extract-archive-docx-index.ps1
# Writes: flareflow-app-snapshot/<live-shipped-dir>/<FF*>/_EXTRACTED_INDEX.md
$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$snapRoot = Join-Path $RepoRoot 'flareflow-app-snapshot'
$liveDirs = @(Get-ChildItem -LiteralPath $snapRoot -Directory -ErrorAction Stop)
$live = $null
foreach ($d in $liveDirs) {
  $hasFf = @(Get-ChildItem -LiteralPath $d.FullName -Directory -ErrorAction SilentlyContinue | Where-Object { $_.Name -like 'FF*' })
  if ($hasFf.Count -ge 1) { $live = $d.FullName; break }
}
if (-not $live) { throw "No folder under flareflow-app-snapshot contains FF*" }
$ffDirs = @(Get-ChildItem -LiteralPath $live -Directory -ErrorAction Stop | Where-Object { $_.Name -like 'FF*' })
if ($ffDirs.Count -lt 1) { throw "No FF* folder under $live" }
$Base = $ffDirs[0].FullName
$Out = Join-Path $Base '_EXTRACTED_INDEX.md'

Add-Type -AssemblyName System.IO.Compression.FileSystem
Add-Type -AssemblyName System.Web

function Get-DocxPlainText([string]$path) {
  $zip = [System.IO.Compression.ZipFile]::OpenRead($path)
  try {
    $ent = $zip.GetEntry('word/document.xml')
    if (-not $ent) { return '[no document.xml]' }
    $sr = New-Object System.IO.StreamReader($ent.Open())
    $xml = $sr.ReadToEnd()
    $sr.Close()
    $xml = $xml -replace '<w:tab[^/]*/>', "`t"
    $xml = $xml -replace '</w:p>', "`n"
    $plain = [regex]::Replace($xml, '<[^>]+>', '')
    $amp = [string][char]38
    $plain = $plain.Replace("${amp}amp;", $amp).Replace("${amp}lt;", [string][char]60).Replace("${amp}gt;", [string][char]62).Replace("${amp}quot;", [string][char]34)
    $plain = ($plain -split "`n" | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' }) -join "`n"
    return $plain
  } finally { $zip.Dispose() }
}

$sb = New-Object System.Text.StringBuilder
$pipe = [char]124
[void]$sb.AppendLine('# FF archive docx - extracted text index')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('> Under flareflow-app-snapshot live-shipped folder / FF* /')
[void]$sb.AppendLine('> Generated by flareflow-app-snapshot/tools/extract-archive-docx-index.ps1')
[void]$sb.AppendLine('')

$files = Get-ChildItem -LiteralPath $Base -Filter '*.docx' -ErrorAction Stop | Sort-Object Name
$nl = [Environment]::NewLine
foreach ($f in $files) {
  $txt = Get-DocxPlainText $f.FullName
  $preview = if ($txt.Length -gt 2500) { $txt.Substring(0, 2500) + $nl + $nl + '... truncated' } else { $txt }
  [void]$sb.AppendLine('---')
  [void]$sb.AppendLine('')
  [void]$sb.AppendLine('## ' + $f.Name)
  [void]$sb.AppendLine('')
  [void]$sb.AppendLine("$pipe Key $pipe Value $pipe")
  [void]$sb.AppendLine("$pipe-----$pipe-------$pipe")
  [void]$sb.AppendLine("$pipe File $pipe " + $f.Name + " $pipe")
  [void]$sb.AppendLine("$pipe Bytes $pipe " + $f.Length + " $pipe")
  [void]$sb.AppendLine("$pipe Modified $pipe " + $f.LastWriteTime.ToString('yyyy-MM-dd HH:mm') + " $pipe")
  [void]$sb.AppendLine("$pipe Chars $pipe " + $txt.Length + " $pipe")
  [void]$sb.AppendLine('')
  [void]$sb.AppendLine('### Preview')
  [void]$sb.AppendLine('')
  [void]$sb.AppendLine('<<<PREVIEW>>>')
  [void]$sb.AppendLine($preview)
  [void]$sb.AppendLine('<<<END>>>')
  [void]$sb.AppendLine('')
}

[System.IO.File]::WriteAllText($Out, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host ([string]::Concat('OK ', $files.Count, ' docx'))
